# Generated by Django 5.2.1 on 2025-06-23 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_inicial_alter_participant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_creación',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='propietario',
        ),
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='participants/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='inicial',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='participants.proyecto'),
        ),
    ]
