# Generated by Django 5.2.1 on 2025-06-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_remove_proyecto_fecha_creación_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='inicial',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
